### ISSUE TITLE
pysha3 uses private 'pystrhex.h' API

### ISSUE THREAD

**Issue by mgorny** [tiran/pysha3#15]
According to PyPy upstream (https://bitbucket.org/pypy/pypy/issues/2687/pypy3-is-missing-pystrhexh-breaking-pysha3) pystrhex.h is a private API of CPython and should not be used in the extensions. I would therefore suggest removing the conditional that uses it and always use the local implementation.

**Comment by tiran** [comment]
master no longer uses ``pystrhex.h``. I also merged another PR to run Travis with pypy. Code is still broken, though.
