### ISSUE TITLE
Support for PyPy3

### ISSUE THREAD

**Issue by carver** [tiran/pysha3#17]
This is a tracking issue for PyPy3 support.

Currently, the missing component is `PyUnicode_New`. I posted that issue to the pypy project:

https://bitbucket.org/pypy/pypy/issues/2723/undefined-symbol-pyunicode_new-in-pypy3

**Comment by tiran** [comment]
Thanks, the function is the preferred way to create unicode objects, from https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_new#c.PyUnicode_New

> This is the recommended way to allocate a new Unicode object. Objects created using this function are not resizable.
> New in version 3.3.

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.
