### ISSUE TITLE
pip3 install prroblem

### ISSUE THREAD

**Issue by dongwangdw** [tiran/pysha3#19]
I got a problem when i installed.
I got error when I try to install it with pip3 install:
`src/64/KeccakF-1600-opt64.c:250:2: error: #error "Not yet implemented"`

But I can install it successfully with the source code.

Is there something I missed?
And I can see from the changes of version, the big endian has been supported.

My os is s390 and it is big endian.

**Comment by WandyLau** [comment]
And I can see from the changes of version, the big endian has been supported.

**Comment by WandyLau** [comment]
I got another sha for python. python-sha3, what is the difference between them? these are not the same, right?

**Comment by tiran** [comment]
Python may select the wrong optimized implementation for your platform.

This package is the official sha3 implementation for Python. It's a standalone version of the sha3 and shake code from Python 3.6.

**Comment by WandyLau** [comment]
Thanks for your reply. I hope so. I will try to see if this can replace that one. Maybe it is the problem of platform? Not sure. I will check it.

**Comment by tiran** [comment]
I'll try to get hold of a S390 machine next week. Could you share more information about your platform? Which OS and compiler are you using?

**Comment by WandyLau** [comment]
I just can install it in s390. In the beginning I mixed this with python-sha3. from the command line:
pip search sha3. I can see the sha3 is python-sha3 not pysha3. This may be the reason, my project chooses the the first one. And the error is from python-sha3 not pysha3. I think we can close this.

**Comment by WandyLau** [comment]
As I see from the code, pysha3 just walk around this big endian problem, which is not implemented yet. And python-sha3, pysha3 use the same code of KeccakCodePackage. So I think it is the problem of KeccakCodePackage. And pysha3 will be a option for us. Not sure if this can work for us.
I will explore it.

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.
