### ISSUE TITLE
Issues with pypi page

### ISSUE THREAD

**Issue by libscott** [tiran/pysha3#2]
Hello,

There appears to be two issues with the pysha3 page on pypi:

* The homepage is set to github.org instead of github.com, didn't load for me, and
* The changelog advertises 1.1.0 and doesn't advertise 1.0.0, which is the latest version I could install.

Cheers

**Comment by pjdelport** [comment]
PR #1 fixes the first of these.

**Comment by tiran** [comment]
I have addressed the second issue, too. It was a typo. The actual release was 1.0.0. I'm pushing 1.0.1 now.
