### ISSUE TITLE
Forget to publish release to pip?

### ISSUE THREAD

**Issue by 0polar** [tiran/pysha3#22]
https://github.com/tiran/pysha3/issues/15 is fixed, but no update on https://pypi.org/project/pysha3/#history.

**Comment by ytrezq** [comment]
@0polar this project hasn’t seen it’s maintainer since 2017. It might be the reason why.

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.
