### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [tiran/pysha3#24]
Problem
---------
On aarch64, ‘pip install pysha3’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install pysha3’ should download the wheels from pypi 

@tiran and @Team Please let me know your interest in releasing aarch64 wheels. I can help in this. To start with could you please tell the steps/Ci you are using to publish the wheel in pypi.

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.
