### ISSUE TITLE
Binary wheels for python 3.8+

### ISSUE THREAD

**Issue by vEpiphyte** [tiran/pysha3#26]
Is it possible to get binary wheels build for python 3.8+?

**Comment by vEpiphyte** [comment]
While I would love to be able to use the hashlib sha3 functions, my use cases involve keccak directly, invoking the `_pysha3.keccak_256()` API.

**Comment by tiran** [comment]
Yes, this project is advertised as ``Backport of hashlib.sha3 for 2.7 to 3.5 ``. Python 2.7 and 3.5 have reached their EOL last year. CPython is going to drop the internal ``_sha3`` module eventually and use SHA-3 from OpenSSL.

**Comment by vEpiphyte** [comment]
Thanks. I am closing this.
